/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tax.cli.app;

import java.io.BufferedReader;
import java.io.IOException;

import com.fasterxml.jackson.databind.ObjectMapper;

import tax.cli.app.Records.StockMarketOperation;

public class App {

    public static void main(String[] args) {
        ObjectMapper objectMapper = new ObjectMapper();
        try (BufferedReader reader = new BufferedReader(new java.io.InputStreamReader(System.in))) {
            var line = reader.readLine();
            OperationProcessor processor = new OperationProcessor();
            while (!line.isEmpty()) {
                StockMarketOperation[] operations = objectMapper.readValue(line, StockMarketOperation[].class);
                var taxes = processor.processOperations(operations);
                System.out.println(objectMapper.writeValueAsString(taxes));
                processor.reset();
                line = reader.readLine();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

    }
}
